### PR TITLE
Fix runtime arg fuzzy matching

### LINKED ISSUE #92: inconsistency with `rtx where`
`rtx where` is a bit overloaded. I think a lot of people want to use it so that they can pick whichever is the current* version  of a runtime. However, in the case where there _isn't_ an active version (like if you run `rtx where python`, but no parent `.tool-versions` file actually has python mentioned, then `rtx where` will show the _latest_ version. (EDIT: as @amoosbr notes, this actually isn't even working properly)

I think in some cases people would prefer this is an error instead.

The reason `rtx where python` shows the latest installed is because that's essentially an alias for running `rtx where python@latest`, which you would expect to show you the latest _installed_ version.

I'm not entirely sure what we want to do here but I think we could make this behave more predictably.

One idea is we could add a `--current` flag to limit `rtx where` to only show active versions. Or we could make it so if you don't specify a version prefix with `@...`, then it only shows current and installed otherwise. I _think_ the latter might be a little more along what users would expect to happen.

(* "current" in rtx-speak means "in a .tool-versions file or otherwise specified, like via `--runtime` or environment variable")

### LINKED ISSUE #119: Bug in semantic version sorting for fuzzy matches with i.e. `rtx exec`
This is probably an issue in the correct semantic version sorting combined with fuzzy version matching.

Expected:
`rtx exec python@3.10 -- python --version` --> `Python 3.10.10`

Actual:
`rtx exec python@3.10 -- python --version` --> `Python 3.10.9`

```sh
❯ rtx global --fuzzy python@3.10 python@3.11
python 3.10 3.11
❯ rtx ls
   python 2.7.18
   python 3.8.10
   python 3.9.12
   python 3.10.10
-> python 3.10.9             (set by ~/.tool-versions)
   python 3.11.1
-> python 3.11.2             (set by ~/.tool-versions)
❯ python --version
Python 3.10.9
❯ rtx exec python@3.10 -- python --version
Python 3.10.9
❯ rtx exec python@3.10.10 -- python --version
Python 3.10.10
```

### PR DESCRIPTION
**Pull request by jdxcode**
Fixes #119
Fixes #92

This fixes a lot of bugs with the 'runtime arg' which is used throughout rtx. It's the argument used in `rtx local RUNTIMEARG`, `rtx where RUNTIMEARG`, `rtx install RUNTIMEARG`, and many more places.

Originally the intention was for this without an "@" to behave the same as "@latest", but it would _also_ sometimes use the version in `.tool-versions`.

This wasn't consistent throughout rtx and broken in several places that's hard to document fully.

What this change does is make a runtime arg like `nodejs` (without an "@"), look up the current version from `.tool-versions`. `nodejs@latest` will always use the latest available release, despite what may be installed. There were attempts to use the latest _installed_ version to avoid a situation where a new runtime is released and this would require installing it, but for now I'm moving away from that model.

So now things are consistent: `nodejs` means `.tool-versions`. `nodejs@latest` means the latest _available_, not latest _installed_.

### CODE REVIEW

**Comment by jdxcode** [comment]
smoke testing seems to be working for this. I would not be surprised if this causes a bug or two because it's a pretty large change that impacts most of the project.

#119 and #92 seem to be resolved for sure though

**Comment by jdxcode** [comment]
# [Codecov](https://codecov.io/gh/jdxcode/rtx/pull/121?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey) Report
Base: **80.83**% // Head: **80.27**% // Decreases project coverage by **`-0.57%`** :warning:
> Coverage data is based on head [(`f3d76ac`)](https://codecov.io/gh/jdxcode/rtx/pull/121?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey) compared to base [(`0ccb4d0`)](https://codecov.io/gh/jdxcode/rtx/commit/0ccb4d09730edea6d70e0e564c54d4875bb9470f?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey).
> Patch coverage: 80.48% of modified lines in pull request are covered.

<details><summary>Additional details and impacted files</summary>


```diff
@@            Coverage Diff             @@
##             main     #121      +/-   ##
==========================================
- Coverage   80.83%   80.27%   -0.57%     
==========================================
  Files          79       79              
  Lines        2437     2459      +22     
==========================================
+ Hits         1970     1974       +4     
- Misses        467      485      +18     
```


| [Impacted Files](https://codecov.io/gh/jdxcode/rtx/pull/121?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey) | Coverage Δ | |
|---|---|---|
| [src/cli/activate.rs](https://codecov.io/gh/jdxcode/rtx/pull/121?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey#diff-c3JjL2NsaS9hY3RpdmF0ZS5ycw==) | `85.71% <ø> (ø)` | |
| [src/cli/env.rs](https://codecov.io/gh/jdxcode/rtx/pull/121?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey#diff-c3JjL2NsaS9lbnYucnM=) | `100.00% <ø> (ø)` | |
| [src/cli/mod.rs](https://codecov.io/gh/jdxcode/rtx/pull/121?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey#diff-c3JjL2NsaS9tb2QucnM=) | `88.46% <ø> (ø)` | |
| [src/cli/render\_help.rs](https://codecov.io/gh/jdxcode/rtx/pull/121?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey#diff-c3JjL2NsaS9yZW5kZXJfaGVscC5ycw==) | `100.00% <ø> (ø)` | |
| [src/cli/args/runtime.rs](https://codecov.io/gh/jdxcode/rtx/pull/121?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey#diff-c3JjL2NsaS9hcmdzL3J1bnRpbWUucnM=) | `75.00% <61.11%> (-15.00%)` | :arrow_down: |
| [src/cli/uninstall.rs](https://codecov.io/gh/jdxcode/rtx/pull/121?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey#diff-c3JjL2NsaS91bmluc3RhbGwucnM=) | `78.57% <70.00%> (-6.05%)` | :arrow_down: |
| [src/cli/latest.rs](https://codecov.io/gh/jdxcode/rtx/pull/121?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey#diff-c3JjL2NsaS9sYXRlc3QucnM=) | `91.66% <80.00%> (-8.34%)` | :arrow_down: |
| [src/config/config\_file/mod.rs](https://codecov.io/gh/jdxcode/rtx/pull/121?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey#diff-c3JjL2NvbmZpZy9jb25maWdfZmlsZS9tb2QucnM=) | `83.33% <83.33%> (-2.39%)` | :arrow_down: |
| [src/config/mod.rs](https://codecov.io/gh/jdxcode/rtx/pull/121?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey#diff-c3JjL2NvbmZpZy9tb2QucnM=) | `83.52% <87.50%> (+2.16%)` | :arrow_up: |
| [src/cli/install.rs](https://codecov.io/gh/jdxcode/rtx/pull/121?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey#diff-c3JjL2NsaS9pbnN0YWxsLnJz) | `87.23% <90.90%> (ø)` | |
| ... and [5 more](https://codecov.io/gh/jdxcode/rtx/pull/121?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey) | |

Help us with your feedback. Take ten seconds to tell us [how you rate us](https://about.codecov.io/nps?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey). Have a feature suggestion? [Share it here.](https://app.codecov.io/gh/feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey)

</details>

[:umbrella: View full report at Codecov](https://codecov.io/gh/jdxcode/rtx/pull/121?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey).   
:loudspeaker: Do you have feedback about the report comment? [Let us know in this issue](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Jeff+Dickey).

**Comment by jdxcode** [comment]
holdon-toyourbutts

File: src/cli/env.rs [hunk 1]
```diff
@@ -82,7 +82,7 @@ mod test {
 
         assert!(stdout.contains(
             dirs::ROOT
-                .join("installs/shfmt/3.5.2/bin")
+                .join("installs/shfmt/3.5.1/bin")
```
Comment (jdx) [inline src/cli/env.rs:85]: I have no idea why this happened I don't see a 3.5.2 ever being released. I'm wondering if this version was yanked?

That doesn't explain why it uses 3.5.2 above though...

Comment (jdx) [reply src/cli/env.rs:85]: ahhhhh this is a bug in asdf-shfmt: it doesn't fail if the version is incorrect

Comment (jdx) [reply src/cli/env.rs:85]: fixed https://github.com/jdxcode/rtx/commit/5cc84c6111306c78d0c7ac911d27a0694b12bd7a
