### PR TITLE
bug: do not put `.rtx-incomplete` file in install directory

### LINKED ISSUE #196: Can't install erlang
Environment: `Linux pop-os 6.1.11-76060111-generic #202302091138~1675975749~22.04~f771a7f SMP PREEMPT_DYNAMIC Thu F x86_64 x86_64 x86_64 GNU/Linux`
rtx version: `1.16.0 linux-x64 (built 2023-02-23)`

When trying to install erlang with rtx the installation always ends up failing with exit code 1.

Output from `RTX_DEBUG=1 RTX_VERBOSE=1 rtx install erlang 25.2.1`
```
[DEBUG] rtx::config: Config:
Files: ~/.tool-versions
Installed Plugins: awscli, elixir, erlang, gleam, golang, java, jq, mc, minio, nodejs, php, python, ruby, rust, shellcheck, shfmt, swiprolog, terraform, tiny, yarn
[DEBUG] rtx::cli: rtx install erlang 25.2.1
[DEBUG] rtx::toolset::builder: Toolset: erlang@25.2.1, nodejs@16.4.0, elixir@1.14.3-otp-25, gleam@0.26.2, yarn@1.22.11, ruby@3.0.3, python@3.10.4, java@adoptopenjdk-17.0.2+8, rust@1.65.0, php@8.1.8, terraform@1.2.7, swiprolog@7.6.4, minio@2022-10-08T20-11-00Z, mc@2022-10-09T21-10-59Z, golang@1.19, awscli@2.9.19
[DEBUG] rtx::runtimes: install erlang@25.2.1 25.2.1
rtx erlang@25.2.1 installing
[DEBUG] rtx::cmd: $ /home/blond/.local/share/rtx/plugins/erlang/bin/install 
rtx erlang@25.2.1   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
rtx erlang@25.2.1                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 98.8M  100 98.8M    0     0  13.4M      0  0:00:07  0:00:07 --:--:-- 15.3M
rtx erlang@25.2.1 APPLICATIONS INFORMATION (See: /home/blond/.local/share/rtx/plugins/erlang/kerl-home/builds/asdf_25.2.1/otp_build_25.2.1.log)
rtx erlang@25.2.1  * wx             : wxWidgets was not compiled with --enable-webview or wxWebView developer package is not installed, wxWebView will NOT be available
rtx erlang@25.2.1 error ✗
Error: 
   0: [erlang] script exited with non-zero status: exit code 1

Location:
   src/plugins/script_manager.rs:182

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

I've also found that building erlang works fine, it's only the last step of "installing" it to the rtx install folder that fails. Running `cp -r ~/.local/share/rtx/plugins/erlang/kerl-home/builds/asdf_25.2.1/otp_src_25.2.1 ~/.local/share/rtx/installs/erlang/25.2.1` finishes the installation and everything works fine.

I can successfully install erlang through asdf, or directly through kerl, so this leads me to believe that something about the way rtx runs installation scripts is messing with the erlang plugin's ability to run properly.

### PR DESCRIPTION
**Pull request by jdxcode**
Creating this file in the installs directory causes erlang to fail to install. This change moves it to the cache directory. Not putting a test in since that will be covered by #182.

Fixes #196
Verified by running `rtx install -f erlang@25.2.1` which fails in main.

### CODE REVIEW

File: src/toolset/tool_version.rs [hunk 1]
```diff
@@ -66,9 +66,6 @@ impl ToolVersion {
             Some(("prefix", p)) => {
                 return self.resolve_prefix(settings, plugin, p);
             }
-            Some(("system", _)) => {
```
Comment (jdx) [inline src/toolset/tool_version.rs:69]: this isn't related but I noticed it was wrong (it was looking for `system:xxx`) and would never get hit
